const ErrorEnum = Object.freeze({
  BAD_REQUEST_ERROR: "BAD_REQUEST_ERROR",
  FORBIDDEN_ERROR: "FORBIDDEN_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  UNAUTHORIZED_ERROR: "UNAUTHORIZED_ERROR",
});

module.exports = ErrorEnum;
