version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=DB_TEST_USER
      - DB_PASSWORD=DB_TEST_PASS
      - DB_NAME=DB_TEST_NAME
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: DB_TEST_USER
      POSTGRES_PASSWORD: DB_TEST_PASS
      POSTGRES_DB: DB_TEST_NAME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
